# This configuration creates one Minecraft instance. No ADS instances are created.
# If you intend to run more than one game server, use the ADS module instead.

services:
  amp:
    container_name: amp
    image: mitchtalmadge/amp-dockerized:latest
    networks:
      default:
        mac_address: 02:42:AC:XX:XX:XX # Please see the README about this field.
    ports:
      - 25565:25565 # For Java Edition (TCP)
      - 19132:19132/udp # For Bedrock Edition (UDP)
      - 25570:8080 # Maybe you already have something running on 8080, so we could map to 25570. Remove if you want to use 8080.
    volumes:
      - ./ampdata:/home/amp/.ampdata
    environment:
      - "UID=120" # Change according to which user on the host will own the ampdata volume.
      - "GID=124"
      - "TZ=Etc/UTC" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - "LICENCE=#########-####-#####-##########"
      - "MODULE=Minecraft"
    restart: unless-stopped
