# This configuration creates one McMyAdmin (Minecraft) instance. No ADS instances are created.

services:
  amp:
    container_name: amp
    image: mitchtalmadge/amp-dockerized:latest
    networks:
      default:
        mac_address: 02:42:AC:XX:XX:XX # Please see the README about this field.
    ports:
      - 25565:25565
      - 25570:8080
    volumes:
      - ./ampdata:/home/amp/.ampdata
    environment:
      - "UID=120" # Change according to which user on the host will own the ampdata volume.
      - "GID=124"
      - "TZ=Etc/UTC" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - "LICENCE=#########-####-#####-##########"
      - "MODULE=McMyAdmin"
    restart: unless-stopped
