name: "Deploy Production"

on:
  push:
    branches:
      - "master"
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: e.g. v22

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      for_deploy: true

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Download Docker Image Artifacts"
        uses: actions/download-artifact@v4
        with:
          path: /tmp
      - name: "Get Tag Name"
        id: get_tag_name
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.tag }}" != "" ]]; then
            echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_OUTPUT
          fi
      - name: "Load Docker Images"
        id: load_images
        run: |
          DOCKERHUB_TAGS=""
          GHCR_TAGS=""
          for f in $(find /tmp -type f -iname 'docker-image-*.tar' -print); do
            ARCH=$(echo ${f} | sed -E 's/.*docker-image-(.*).tar/\1/')
            docker load --input ${f}
            
            # Tag for Docker Hub
            DOCKERHUB_TAG="mitchtalmadge/amp-dockerized:${{ steps.get_tag_name.outputs.TAG_NAME }}-${ARCH}"
            DOCKERHUB_TAGS="${DOCKERHUB_TAGS} ${DOCKERHUB_TAG}"
            docker tag amp-dockerized:latest ${DOCKERHUB_TAG}
            
            # Tag for GHCR
            GHCR_TAG="ghcr.io/mitchtalamadge/amp-dockerized:${{ steps.get_tag_name.outputs.TAG_NAME }}-${ARCH}"
            GHCR_TAGS="${GHCR_TAGS} ${GHCR_TAG}"
            docker tag amp-dockerized:latest ${GHCR_TAG}
          done
          echo "DOCKERHUB_TAGS=${DOCKERHUB_TAGS}" >> $GITHUB_OUTPUT
          echo "GHCR_TAGS=${GHCR_TAGS}" >> $GITHUB_OUTPUT
          docker image ls -a
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Deploy to Docker Hub"
        run: docker image push --all-tags mitchtalmadge/amp-dockerized
      - name: "Deploy to GitHub Container Registry"
        run: docker image push --all-tags ghcr.io/mitchtalamadge/amp-dockerized
      - name: "Deploy Multi-Arch Manifests"
        run: |
          # Docker Hub manifests
          DOCKERHUB_MANIFESTS="mitchtalmadge/amp-dockerized:latest mitchtalmadge/amp-dockerized:${{ steps.get_tag_name.outputs.TAG_NAME }}"
          for m in ${DOCKERHUB_MANIFESTS}; do
            docker manifest create ${m} ${{ steps.load_images.outputs.DOCKERHUB_TAGS }}
            docker manifest push ${m}
          done
          
          # GHCR manifests
          GHCR_MANIFESTS="ghcr.io/mitchtalamadge/amp-dockerized:latest ghcr.io/mitchtalamadge/amp-dockerized:${{ steps.get_tag_name.outputs.TAG_NAME }}"
          for m in ${GHCR_MANIFESTS}; do
            docker manifest create ${m} ${{ steps.load_images.outputs.GHCR_TAGS }}
            docker manifest push ${m}
          done
